### ISSUE TITLE
django-slack.readthedocs.io is not rendering correctly

### ISSUE THREAD

**Issue by actongorton** [lamby/django-slack#78] opened 2017-11-13 22:22 UTC
Just a head's up that the docs aren't rendering with any styles, looks like plain & unformatted html: django-slack.readthedocs.io

**Comment by lamby** [comment] 2017-11-15 03:44
Indeed. Not sure what the issue is. Can you help?


See also:

https://github.com/lamby/django-slack/pull/76

**Comment by davidfischer** [comment] 2018-06-08 04:15
I am not sure why this happened but I believe this issue is fixed on Read the Docs. If you trigger a build [here](https://readthedocs.org/projects/django-slack/builds/) I think it should *just work*.

I ran a quick test import [here](https://django-slack-test.readthedocs.io/en/latest/)

**Comment by lamby** [comment] 2018-06-08 07:40
Rebuild requested!

**Comment by davidfischer** [comment] 2018-06-08 13:03
Bizarre, that didn't fix it. I'll dig deeper.

**Comment by davidfischer** [comment] 2018-06-08 17:01
This appears to be a bug in the Single Page HTML build option. I'm digging deeper. There's a [bug on Read the Docs](https://github.com/rtfd/readthedocs.org/issues/4162) for it and I'm going to see if I can get it resolved.

<img width="899" alt="screen shot 2018-06-08 at 9 59 37 am" src="https://user-images.githubusercontent.com/185043/41170785-b7ff4218-6b02-11e8-8cf7-7db08fbfca9f.png">

**Comment by davidfischer** [comment] 2018-06-08 19:13
I was able to track this down to a bug across the Read the Docs theme and the Read the Docs sphinx extensions. This is fixed in master on Read the Docs so it should just build correctly after the next deploy (next week). In the meantime, just switch "Sphinx Single Page HTML" to "Sphinx Html" and it should work correctly.

**Comment by lamby** [comment] 2018-06-08 21:34
> switch "Sphinx Single Page HTML" to "Sphinx Html" and it should work correctly

One sec... building... https://django-slack.readthedocs.io/ hurrah! (hard refresh needed, mind..)

**Comment by lamby** [comment] 2018-06-08 21:34
Closing issue - feel free to re-open!

**Comment by lamby** [comment] 2018-06-08 21:35
Thanks!

**Closed by lamby** 2018-06-08 21:34 UTC
